name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Setup git user
        run: |
          git config --global user.name "maciek-bot"
          git config --global user.email "maciek.gh.bot@gmail.com"
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: Release
          commit: Release
          setupGitUser: false
          publish: bun run publish
          version: bun run version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_PAT }}
